export { Query as Info } from './Info';
export { Query as Layout } from './Layout';
export { Query as Media } from './Media';
export { Query as Page } from './Page';
export { Query as Plugin } from './Plugin';
export { Query as Quotas } from './Quotas';
export { Query as Role } from './Role';
export { Query as Theme } from './Theme';
export { Query as User } from './User';
