"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Hooks = exports.Components = void 0;
const tslib_1 = require("tslib");
const Preact = tslib_1.__importStar(require("preact"));
const graphql_react_1 = require("graphql-react");
const App_1 = tslib_1.__importDefault(require("./App"));
const Graph_1 = require("./Graph");
Preact.render(Preact.h(graphql_react_1.GraphQLProvider, { graphql: Graph_1.graphql }, Preact.h(App_1.default, null)), document.getElementById('root'));
exports.Components = tslib_1.__importStar(require("./export/Components"));
exports.Hooks = tslib_1.__importStar(require("./export/Hooks"));
