"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Plugins = exports.Themes = exports.Users = exports.Roles = exports.Media = exports.Main = void 0;
var MainSettings_1 = require("./MainSettings");
Object.defineProperty(exports, "Main", { enumerable: true, get: function () { return __importDefault(MainSettings_1).default; } });
var MediaSettings_1 = require("./MediaSettings");
Object.defineProperty(exports, "Media", { enumerable: true, get: function () { return __importDefault(MediaSettings_1).default; } });
var RolesSettings_1 = require("./RolesSettings");
Object.defineProperty(exports, "Roles", { enumerable: true, get: function () { return __importDefault(RolesSettings_1).default; } });
var UsersSettings_1 = require("./UsersSettings");
Object.defineProperty(exports, "Users", { enumerable: true, get: function () { return __importDefault(UsersSettings_1).default; } });
var ThemesSettings_1 = require("./ThemesSettings");
Object.defineProperty(exports, "Themes", { enumerable: true, get: function () { return __importDefault(ThemesSettings_1).default; } });
var PluginsSettings_1 = require("./PluginsSettings");
Object.defineProperty(exports, "Plugins", { enumerable: true, get: function () { return __importDefault(PluginsSettings_1).default; } });
