name: release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Use Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Update NPM
      run: sudo npm install -g npm@latest
      
    - name: Install and Link Dependencies
      run: npm run install
    
    - name: Build Application
      run: npm run build
      
    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: Linux
        path: modules/server/dist/server-linux
    
    - name: Upload MacOS Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: MacOS
        path: modules/server/dist/server-macos
    
    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: Windows
        path: modules/server/dist/server-win.exe
